server:
  port: 5093

spring:
  application:
    name: apix-memory

  datasource:
    url: jdbc:mysql://localhost:3306/apix_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: apix
    password: apixapix
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  redis:
    host: localhost
    port: 6379
    database: 0
